<?php return [

	'statuses' => [
		'10' => 'new',
		'20' => 'feedback',
		'30' => 'acknowledged',
		'40' => 'confirmed',
		'50' => 'assigned',
		'80' => 'resolved',
		'90' => 'closed',
	],

	'view_page_fields' => [
		'additional_info',
		'attachments',
		'category_id',
		'date_submitted',
		'description',
		'due_date',
		'eta',
		'fixed_in_version',
		'handler',
		'id',
		'last_updated',
		'os',
		'os_version',
		'platform',
		'priority',
		'product_build',
		'product_version',
		'project',
		'projection',
		'reporter',
		'reproducibility',
		'resolution',
		'severity',
		'status',
		'steps_to_reproduce',
		'summary',
		'tags',
		'target_version',
		'view_state',
	],
	
	'report_page_fields' => [
		'additional_info',
		'attachments',
		'category_id',
		'due_date',
		'handler',
		'os',
		'os_version',
		'platform',
		'priority',
		'product_build',
		'product_version',
		'reproducibility',
		'severity',
		'steps_to_reproduce',
		'target_version',
		'view_state',
	]
	
];